import { useState } from 'react'
import { Activity, ArrowLeft, ArrowUpRight, Check, CheckCheck, Copy, ExternalLink, FlaskConical, MoreHorizontal, Plus, Send, ShieldCheck, Timer, TriangleAlert, Webhook, X } from 'lucide-react'
import { useLocation, useNavigate } from 'react-router-dom'
import { webhookFixtures, type WebhookEndpoint } from './fixtures'

function EndpointStatus({ value }: { value: WebhookEndpoint['status'] }) { return <span className={`status status--${value === 'Healthy' ? 'delivered' : 'pending'}`}><i>{value === 'Healthy' ? <Check size={12} /> : <TriangleAlert size={12} />}</i>{value}</span> }

export function WebhooksPage() {
  const location = useLocation(); const navigate = useNavigate(); const id = location.pathname.startsWith('/webhooks/') ? location.pathname.split('/')[2] : undefined; const endpoint = webhookFixtures.find(item => item.id === id)
  return endpoint ? <WebhookDetail endpoint={endpoint} onBack={() => navigate('/webhooks')} /> : <WebhookList onOpen={id => navigate(`/webhooks/${id}`)} />
}

function WebhookList({ onOpen }: { onOpen: (id: string) => void }) {
  const [createOpen, setCreateOpen] = useState(false); const [endpoints, setEndpoints] = useState(webhookFixtures)
  return <><section className="webhook-stats"><Stat icon={<CheckCheck size={16} />} value="99.98%" label="Success rate" color="green" /><Stat icon={<Activity size={16} />} value="428,104" label="Events this month" color="blue" /><Stat icon={<Timer size={16} />} value="186ms" label="Average response" color="violet" /></section><section className="panel endpoints-panel"><div className="panel__header"><div><h2>Endpoints</h2><p>Configured destinations for your workspace events.</p></div><button className="button button--primary" onClick={() => setCreateOpen(true)}><Plus size={14} />Add endpoint</button></div><div className="endpoint-list">{endpoints.map(endpoint => <button className="endpoint-row" key={endpoint.id} onClick={() => onOpen(endpoint.id)}><span className={`endpoint-row__icon ${endpoint.environment === 'Test' ? 'endpoint-row__icon--test' : endpoint.status === 'Degraded' ? 'endpoint-row__icon--warning' : ''}`}>{endpoint.environment === 'Test' ? <FlaskConical size={17} /> : endpoint.status === 'Degraded' ? <TriangleAlert size={17} /> : <Webhook size={17} />}</span><span className="endpoint-row__main"><strong>{endpoint.name}</strong><code>{endpoint.url}</code><small>{endpoint.events.slice(0, 2).map(event => <span className="event-pill" key={event}>{event}</span>)}{endpoint.events.length > 2 && <span className="event-pill">+{endpoint.events.length - 2}</span>}</small></span><span className="endpoint-row__health"><EndpointStatus value={endpoint.status} /><small>{endpoint.status === 'Healthy' ? `Last success ${endpoint.lastSuccess}` : endpoint.lastSuccess}</small></span><ArrowUpRight className="domain-row__arrow" size={16} /></button>)}</div></section><section className="panel attempts-panel"><div className="panel__header"><div><h2>Recent attempts</h2><p>Latest webhook deliveries across all endpoints.</p></div><button className="text-link" onClick={() => onOpen('wh_prod')}>View all attempts <ArrowUpRight size={14} /></button></div><AttemptsTable /></section>{createOpen && <CreateWebhookDialog onClose={() => setCreateOpen(false)} onCreated={endpoint => { setEndpoints(current => [endpoint, ...current]); setCreateOpen(false) }} />}</>
}

function Stat({ icon, value, label, color }: { icon: React.ReactNode; value: string; label: string; color: string }) { return <div><span className={`metric-icon metric-icon--${color}`}>{icon}</span><span><strong>{value}</strong><small>{label}</small></span></div> }

function AttemptsTable() { const attempts = [['email.delivered', 'Production events', '200 OK', '142ms', '1 min ago'], ['email.bounced', 'Production events', '204 No Content', '196ms', '4 min ago'], ['email.complained', 'Analytics pipeline', '503 Unavailable', '2.8s', '7 min ago']]; return <div className="table-wrap"><table className="data-table webhook-table"><thead><tr><th>Event</th><th>Endpoint</th><th>Response</th><th>Duration</th><th>Attempted</th><th /></tr></thead><tbody>{attempts.map(([event, endpoint, response, duration, attempted]) => <tr key={event}><td><code>{event}</code></td><td>{endpoint}</td><td><span className={`http-code ${response.startsWith('5') ? 'http-code--danger' : 'http-code--success'}`}>{response}</span></td><td>{duration}</td><td className="muted">{attempted}</td><td><button className="icon-button icon-button--small" aria-label="Open attempt"><ArrowUpRight size={14} /></button></td></tr>)}</tbody></table></div> }

function CreateWebhookDialog({ onClose, onCreated }: { onClose: () => void; onCreated: (endpoint: WebhookEndpoint) => void }) { const [name, setName] = useState(''); const [url, setUrl] = useState(''); return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="webhook-title"><div className="modal__header"><div><p className="eyebrow">Event delivery</p><h2 id="webhook-title">Add a webhook endpoint</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={16} /></button></div><form className="form-stack" onSubmit={event => { event.preventDefault(); onCreated({ id: `wh_${Date.now()}`, name: name.trim(), url: url.trim(), environment: 'Production', events: ['email.delivered', 'email.bounced'], status: 'Healthy', lastSuccess: 'Not delivered yet' }) }}><label className="field"><span>Endpoint name</span><input value={name} onChange={event => setName(event.target.value)} placeholder="Production events" required /></label><label className="field"><span>Endpoint URL</span><input type="url" value={url} onChange={event => setUrl(event.target.value)} placeholder="https://api.example.com/webhooks" required /></label><fieldset className="permission-field"><legend>Events</legend><label><input type="checkbox" defaultChecked /> Delivered</label><label><input type="checkbox" defaultChecked /> Bounced</label><label><input type="checkbox" /> Complained</label><label><input type="checkbox" /> Opened and clicked</label></fieldset><div className="modal__footer"><button className="button button--secondary" type="button" onClick={onClose}>Cancel</button><button className="button button--primary" type="submit"><Webhook size={14} />Create endpoint</button></div></form></section></div> }

function WebhookDetail({ endpoint, onBack }: { endpoint: WebhookEndpoint; onBack: () => void }) { const [copied, setCopied] = useState(false); const secret = 'whsec_........f7d2'; const copy = async () => { await navigator.clipboard?.writeText(secret); setCopied(true) }; return <><div className="back-link-wrap"><button className="back-link" onClick={onBack}><ArrowLeft size={14} />Back to webhooks</button></div><section className="detail-heading"><div><div className="detail-heading__title"><span className="message-cell__icon message-cell__icon--large webhook-detail-icon"><Webhook size={17} /></span><div><p className="eyebrow">Webhook endpoint</p><h1>{endpoint.name}</h1></div></div><div className="detail-meta"><EndpointStatus value={endpoint.status} /><span className="detail-meta__dot">.</span><code>{endpoint.url}</code></div></div><div className="page-heading__actions"><button className="button button--secondary"><Send size={14} />Send test</button></div></section><section className="webhook-detail-stats"><div><strong>99.98%</strong><span>Success rate</span></div><div><strong>142ms</strong><span>Average response</span></div><div><strong>428,104</strong><span>Events delivered</span></div><div><strong>{endpoint.events.length}</strong><span>Subscribed events</span></div></section><section className="content-grid webhook-detail-grid"><div className="detail-main"><article className="panel attempts-panel"><div className="panel__header"><div><h2>Delivery attempts</h2><p>Recent requests sent to this endpoint.</p></div></div><AttemptsTable /></article><article className="panel code-panel"><div className="panel__header"><div><h2>Latest payload</h2><p>Event body sent to your endpoint</p></div><button className="icon-button" aria-label="Copy payload"><Copy size={14} /></button></div><pre><code>{JSON.stringify({ type: 'email.delivered', id: 'evt_01H9K8D4QW', created_at: '2026-08-18T10:42:18Z', data: { email_id: 'msg_01H9K8D4QW', to: 'jordan@northstar.io', domain: 'mail.acme.dev' } }, null, 2)}</code></pre></article></div><aside className="detail-aside"><article className="panel subscriptions-panel"><div className="panel__header"><div><h2>Subscribed events</h2><p>Events sent to this endpoint</p></div></div><div className="subscription-list">{endpoint.events.map(event => <span key={event}><Check size={14} />{event}</span>)}</div></article><article className="panel signing-panel"><div className="panel__header"><div><h2>Signing secret</h2><p>Verify every request came from Signal Mail.</p></div><ShieldCheck size={17} /></div><div className="secret-field"><code>{secret}</code><button className="icon-button icon-button--small" onClick={copy} aria-label="Copy signing secret"><Copy size={14} /></button></div><small className="muted">{copied ? 'Copied to clipboard.' : 'Keep this secret in your server environment.'}</small></article></aside></section></> }

