import { useCallback, useEffect, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { Activity, Globe2, KeyRound, LogOut, Mail, Menu, Send, ShieldBan, Webhook, X, BookOpen } from 'lucide-react'
import { api, ApiError } from '../../lib/api/client'
import { Envelope, Environment, Session, ErrorNotice, Panel, Refresh, errorText, useAction } from './shared'
import { Authentication } from './Authentication'
import { Domains, Emails, Keys, Suppressions, Webhooks } from './Pages'
import { SendDialog } from './SendDialog'
import './console.css'

function DeveloperDocs() {
  return <Panel title="Integrate with the API"><p>Create a test key with emails:send and emails:read. Keep the secret on your server.</p><pre>{`curl ${window.location.origin}/api/v1/emails \\\n  -H "Authorization: Bearer $MAILER_API_KEY" \\\n  -H "Idempotency-Key: order-123-confirmation" \\\n  -H "Content-Type: application/json" \\\n  -d '{"from":"sender@sandbox.mailer.invalid","to":["you@example.com"],"subject":"Hello","text":"Your first test email"}'`}</pre><p>Read status using GET /v1/emails/{'{id}'}. List with GET /v1/emails?limit=25&amp;offset=0. A production key requires a verified sender domain.</p><p>Test delivery defaults to delivered. Use <code>bounce@simulator.mailer.invalid</code> or <code>complaint@simulator.mailer.invalid</code> to exercise feedback and suppression. Only test keys simulate these addresses.</p><h3>Webhook verification</h3><p>Verify raw request bytes before parsing JSON. Sign <code>webhook-id + "." + webhook-timestamp + "." + rawBody</code> using HMAC-SHA256, with the complete whsec_ secret as the UTF-8 key. Compare the unpadded base64url digest to the value after <code>v1,</code> in webhook-signature using constant-time comparison. Reject timestamps more than five minutes away and deduplicate webhook-id.</p><p>Payloads use names such as email.delivery. data.emailId matches the send response, and data.environment separates test and production. Deliveries are at least once; receivers must be idempotent and return 2xx promptly.</p><h3>Release scope</h3><p>Up to 50 total To/CC/BCC recipients, text/HTML, reply_to, metadata, and attachments. Custom headers/tags, templates, billing, MFA, and team management are not offered in this private release. The monthly limit counts accepted message submissions, including tests; it is not a billing meter or the AWS recipient quota.</p></Panel>
}
const navigation = [{ path: '/', label: 'Overview', icon: Activity }, { path: '/emails', label: 'Emails', icon: Mail }, { path: '/domains', label: 'Domains', icon: Globe2 }, { path: '/api-keys', label: 'API keys', icon: KeyRound, admin: true }, { path: '/webhooks', label: 'Webhooks', icon: Webhook, admin: true }, { path: '/suppressions', label: 'Suppressions', icon: ShieldBan, admin: true }, { path: '/developers', label: 'API guide', icon: BookOpen }]
export default function Console() {
  const [session, setSession] = useState<Session | null>(null), [loading, setLoading] = useState(true), [sessionError, setSessionError] = useState('')
  const [environment, setEnvironment] = useState<Environment>('test'), [sendOpen, setSendOpen] = useState(false), [mobileOpen, setMobileOpen] = useState(false), [revision, setRevision] = useState(0)
  const navigate = useNavigate(), location = useLocation(), action = useAction()
  const loadSession = useCallback(async () => {
    try { const value = await api.get<Envelope<Session>>('/v1/auth/session'); setSession(value.data); setSessionError('') } catch (error) {
      if (error instanceof ApiError && error.status === 401) setSession(null); else setSessionError(errorText(error))
    } finally { setLoading(false) }
  }, [])
  useEffect(() => { void loadSession(); const expired = () => { setSession(null); setSendOpen(false) }; window.addEventListener('mailer:session-expired', expired); return () => window.removeEventListener('mailer:session-expired', expired) }, [loadSession])
  if (loading) return <main className="live-auth" role="status">Loading your workspace…</main>
  if (sessionError && !session) return <main className="live-auth"><ErrorNotice error={sessionError} /><Refresh reload={() => void loadSession()} /></main>
  if (!session || ['/forgot-password', '/reset-password', '/verify-email', '/resend-verification'].includes(location.pathname)) return <Authentication signedIn={setSession} />
  const admin = ['owner', 'admin'].includes(session.user.role)
  const route = navigation.find(item => item.path === location.pathname && (!item.admin || admin)) ?? navigation[0]
  function go(path: string) { navigate(path); setMobileOpen(false) }
  const page = route.path === '/emails' ? <Emails environment={environment} /> : route.path === '/domains' ? <Domains admin={admin} /> : route.path === '/api-keys' ? <Keys productionEnabled={session.workspace.production_enabled} /> : route.path === '/webhooks' ? <Webhooks /> : route.path === '/suppressions' ? <Suppressions /> : route.path === '/developers' ? <DeveloperDocs /> : <><div className="metric-grid live-metrics"><Panel title="Monthly submissions"><strong className="metric-card__value">{session.workspace.usage.sent.toLocaleString()}</strong><p>of {session.workspace.usage.limit.toLocaleString()} accepted-message limit, including tests</p></Panel><Panel title="Current environment"><strong className="metric-card__value">{environment}</strong><p>{environment === 'test' ? 'Simulated delivery. No recipient email.' : 'Real email through your SES account.'}</p></Panel></div><Panel title="Get your integration running"><ol className="live-steps"><li>Create a test key and send from sender@sandbox.mailer.invalid.</li><li>Add a test webhook to verify signed delivery events.</li><li>Verify your domain and SES production access, then switch to a production key.</li></ol><button className="button button--secondary" onClick={() => go('/developers')}>Read the API guide</button></Panel><Emails environment={environment} /></>
  return <div className="app-shell"><aside className={`sidebar ${mobileOpen ? 'is-open' : ''}`}><div className="sidebar__top"><button className="brand" onClick={() => go('/')}><span className="brand__mark"><img src="/crescentsphere-mark.svg" alt="" /></span><span className="brand__name">Crescent<span>mail</span></span></button><button className="icon-button sidebar__close" aria-label="Close navigation" onClick={() => setMobileOpen(false)}><X size={16} /></button></div><div className="workspace-switcher"><div className="workspace-switcher__copy"><span className="eyebrow">Workspace</span><strong>{session.workspace.name}</strong></div></div><nav className="nav" aria-label="Primary navigation">{navigation.filter(item => !item.admin || admin).map(item => <button className={`nav__item ${route.path === item.path ? 'nav__item--active' : ''}`} key={item.path} onClick={() => go(item.path)}><item.icon size={16} />{item.label}</button>)}</nav><div className="sidebar__bottom"><p><strong>{session.user.name}</strong><br /><small>{session.user.email} · {session.user.role}</small></p><ErrorNotice error={action.error} /><button className="nav__item" disabled={action.busy} onClick={() => action.run(async () => { await api.post('/v1/auth/logout', {}); setSession(null); navigate('/login') })}><LogOut size={16} />Sign out</button></div></aside><main className="main-content"><header className="topbar"><button className="icon-button menu-trigger" aria-label="Open navigation" onClick={() => setMobileOpen(true)}><Menu size={18} /></button><strong>{route.label}</strong><div className="topbar__actions"><label className="live-environment">Environment<select aria-label="Environment" value={environment} onChange={e => { setEnvironment(e.target.value as Environment); setSendOpen(false) }}><option value="test">Test</option><option value="production" disabled={!session.workspace.production_enabled}>Production{session.workspace.production_enabled ? '' : ' — approval required'}</option></select></label></div></header><div className="page-wrap react-page"><section className="page-heading"><div><p className="eyebrow">{session.workspace.name}</p><h1>{route.label}</h1></div>{admin && <button className="button button--primary" onClick={() => setSendOpen(true)}><Send size={15} />Send email</button>}</section><ErrorNotice error={sessionError} /><div key={`${route.path}:${revision}`}>{page}</div><footer className="page-footer">CrescentSphere Mailer · Public beta</footer></div></main>{mobileOpen && <button className="mobile-sidebar-backdrop" aria-label="Close navigation" onClick={() => setMobileOpen(false)} />}{sendOpen && <SendDialog environment={environment} close={() => setSendOpen(false)} queued={() => { setRevision(value => value + 1); void loadSession() }} />}</div>
}
