import { useEffect, useRef, useState } from 'react'
import { api } from '../../lib/api/client'
import { Badge, date, Delivery, Domain, Email, Endpoint, Envelope, Environment, ErrorNotice, Field, Key, Panel, Refresh, Secret, Submit, Suppression, useAction, useResource } from './shared'

export function Emails({ environment }: { environment: Environment }) {
  const [offset, setOffset] = useState(0), [selected, setSelected] = useState<string | null>(null)
  const list = useResource<Email[]>(`/v1/emails?environment=${environment}&limit=25&offset=${offset}`, true)
  const detail = useResource<Email>(selected ? `/v1/emails/${selected}` : null, !!selected)
  useEffect(() => { setOffset(0); setSelected(null) }, [environment])
  return <><Panel title={`${environment === 'test' ? 'Test' : 'Production'} email activity`} action={<Refresh reload={list.reload} />}><ErrorNotice error={list.error} />{list.loading && <p role="status">Loading activity…</p>}
    <div className="table-wrap"><table className="data-table"><thead><tr><th>Message</th><th>Recipients</th><th>Status</th><th>Accepted</th><th /></tr></thead><tbody>{list.result?.data.map(email => <tr key={email.id}><td><strong>{email.subject}</strong><code className="live-id">{email.id}</code></td><td>{email.recipients.map(r => r.address).join(', ')}</td><td><Badge value={email.status} /></td><td>{date(email.acceptedAt)}</td><td><button className="text-link" onClick={() => setSelected(email.id)}>Details</button></td></tr>)}</tbody></table></div>
    {!list.loading && !list.result?.data.length && !list.error && <p>No messages in this environment yet.</p>}<div className="live-actions"><button className="button button--secondary" disabled={!offset || list.loading} onClick={() => setOffset(Math.max(0, offset - 25))}>Previous</button><button className="button button--secondary" disabled={!list.result?.hasMore || list.loading} onClick={() => setOffset(offset + 25)}>Next</button></div>
  </Panel>{selected && <Panel title="Message details" action={<button className="text-link" onClick={() => setSelected(null)}>Close</button>}><ErrorNotice error={detail.error} />{detail.loading && <p>Loading…</p>}{detail.result && <><p><strong>{detail.result.data.subject}</strong> · <Badge value={detail.result.data.status} /></p><ErrorNotice error={detail.result.data.lastError} /><p>From: {detail.result.data.from}</p><pre>{JSON.stringify(detail.result.data.recipients, null, 2)}</pre><h3>Content</h3>{detail.result.data.contentAvailable ? <pre>{detail.result.data.content?.text || detail.result.data.content?.html || '(No readable body)'}</pre> : <p>Content expired or is temporarily unavailable.</p>}<h3>Metadata</h3><pre>{JSON.stringify(detail.result.data.metadata, null, 2)}</pre><h3>Delivery events (latest 100)</h3><pre>{JSON.stringify(detail.result.data.events, null, 2)}</pre></>}</Panel>}</>
}

export function Domains({ admin, onProductionReady }: { admin: boolean; onProductionReady?: () => void }) {
  const list = useResource<Domain[]>('/v1/domains'), action = useAction(), [selected, setSelected] = useState<string | null>(null)
  const detail = useResource<Domain>(selected ? `/v1/domains/${selected}` : null)
  const pending = useRef<string[]>([]), checking = useRef(false), [autoError, setAutoError] = useState('')
  const dnsResult = new URLSearchParams(window.location.hash.split('?')[1] ?? '').get('dns')
  pending.current = list.result?.data.filter(domain => domain.status === 'pending').map(domain => domain.id) ?? []
  useEffect(() => {
    if (!selected && pending.current.length > 0) setSelected(pending.current[0])
  }, [selected, list.result])
  useEffect(() => {
    if (!admin) return
    let cancelled = false
    const verifyPending = async () => {
      if (document.hidden || checking.current || pending.current.length === 0) return
      checking.current = true; setAutoError('')
      try {
        let productionReady = false
        for (const id of pending.current) {
          const result = await api.post<Envelope<{ verified: boolean }>>(`/v1/domains/${id}/verify`, {})
          productionReady ||= result.data.verified
        }
        if (productionReady) onProductionReady?.()
        if (!cancelled) { list.reload(); if (selected) detail.reload() }
      } catch (error) {
        if (!cancelled) setAutoError(error instanceof Error ? error.message : 'Automatic verification will retry.')
      } finally {
        checking.current = false
      }
    }
    const first = window.setTimeout(() => void verifyPending(), 1500)
    const timer = window.setInterval(() => void verifyPending(), 15000)
    const visible = () => { if (!document.hidden) void verifyPending() }
    document.addEventListener('visibilitychange', visible)
    return () => { cancelled = true; window.clearTimeout(first); window.clearInterval(timer); document.removeEventListener('visibilitychange', visible) }
  }, [admin, selected, list.reload, detail.reload, onProductionReady])
  return <><Panel title="Sending domains" action={<Refresh reload={list.reload} />}><p>Add a domain you control and publish the DNS records at its DNS provider. Pending records are checked automatically. Use MX priority <strong>10</strong>; publish SPF/DMARC as TXT. Never proxy DKIM records in Cloudflare.</p>
    <ErrorNotice error={autoError} />
    {admin && <form className="live-inline-form" onSubmit={e => { e.preventDefault(); const form = e.currentTarget, domain = String(new FormData(form).get('domain')); action.run(async () => { const value = await api.post<Envelope<Domain>>('/v1/domains', { domain }); form.reset(); list.reload(); setSelected(value.data.id) }) }}><Field label="Domain"><input name="domain" placeholder="mail.example.com" required /></Field><Submit busy={action.busy}>Add domain</Submit></form>}
    <ErrorNotice error={action.error || list.error} />{list.loading && <p>Loading domains…</p>}<div className="table-wrap"><table className="data-table"><thead><tr><th>Domain</th><th>Status</th><th>Actions</th></tr></thead><tbody>{list.result?.data.map(domain => <tr key={domain.id}><td>{domain.domain}</td><td><Badge value={domain.status} /></td><td className="live-actions"><button className="text-link" onClick={() => setSelected(domain.id)}>DNS records</button>{admin && <><button className="text-link" disabled={action.busy} onClick={() => action.run(async () => { const result = await api.post<Envelope<{ verified: boolean }>>(`/v1/domains/${domain.id}/verify`, {}); if (result.data.verified) onProductionReady?.(); list.reload(); detail.reload() })}>Verify</button>{domain.provider === 'stalwart' && <button className="text-link" disabled={action.busy} onClick={() => { if (confirm(`Rotate DKIM for ${domain.domain}? You must publish the new TXT record before sending resumes.`)) action.run(async () => { await api.post(`/v1/domains/${domain.id}/rotate-dkim`, {}); setSelected(domain.id); list.reload(); detail.reload() }) }}>Rotate DKIM</button>}<button className="text-link" disabled={action.busy} onClick={() => { if (confirm(`Disable ${domain.domain}? Production sends from it will fail.`)) action.run(async () => { await api.delete(`/v1/domains/${domain.id}`); list.reload(); setSelected(null) }) }}>Disable</button></>}</td></tr>)}</tbody></table></div>{!list.loading && !list.result?.data.length && <p>No sending domains. Test sends can use sender@sandbox.mailer.invalid without DNS setup.</p>}</Panel>
    {selected && <Panel title="DNS setup" action={<button className="text-link" onClick={() => setSelected(null)}>Close</button>}><ErrorNotice error={detail.error} />{dnsResult === 'published' && <p className="live-notice">DNS records were added. Verification will update automatically as they become public.</p>}{dnsResult && dnsResult !== 'published' && <ErrorNotice error={dnsResult === 'cancelled' ? 'Cloudflare authorization was cancelled.' : dnsResult === 'expired' ? 'Cloudflare authorization expired. Start it again.' : 'Cloudflare could not add every record. Existing records were left unchanged; review the DNS table or try again.'} />}{detail.loading && <p>Loading DNS records…</p>}{admin && detail.result?.data.dns_automation.includes('cloudflare') && detail.result.data.status === 'pending' && <div><button className="button button--primary" disabled={action.busy} onClick={() => action.run(async () => { const value = await api.post<Envelope<{ authorizationUrl: string }>>(`/v1/domains/${selected}/dns-automation/cloudflare`, {}); window.location.assign(value.data.authorizationUrl) })}>Add records with Cloudflare</button><p className="muted">Sign in to Cloudflare and authorize DNS access. Mailer uses it once to add these records, then revokes the token.</p></div>}<ErrorNotice error={action.error} /><div className="table-wrap"><table className="data-table"><thead><tr><th>Type</th><th>Name</th><th>Value</th><th>Purpose</th><th>Status</th></tr></thead><tbody>{detail.result?.data.records.map(record => <tr key={record.name}><td>{['SPF', 'DMARC'].includes(record.record_type) ? `TXT (${record.record_type})` : record.record_type}</td><td><code>{record.name}</code></td><td><code>{record.value}</code></td><td>{record.required ? 'Required' : 'Recommended'}</td><td><Badge value={record.status} /></td></tr>)}</tbody></table></div></Panel>}
  </>
}
const scopes = ['emails:send', 'emails:read', 'domains:read', 'domains:write', 'webhooks:manage', 'suppressions:manage', 'workspace:read']
export function Keys({ productionEnabled }: { productionEnabled: boolean }) {
  const list = useResource<Key[]>('/v1/api-keys'), action = useAction(), [secret, setSecret] = useState('')
  return <><Panel title="Create an API key">{!productionEnabled && <p className="live-notice">Verify a sending domain to unlock production API keys. Test keys and simulated delivery are available now.</p>}<form className="form-stack" onSubmit={e => { e.preventDefault(); const form = e.currentTarget, data = new FormData(form); action.run(async () => { const value = await api.post<Envelope<{ secret: string }>>('/v1/api-keys', { name: data.get('name'), environment: data.get('environment'), scopes: data.getAll('scopes'), expires_in_days: Number(data.get('expiry')) }); setSecret(value.data.secret); form.reset(); list.reload() }) }}><div className="form-two"><Field label="Name"><input name="name" required maxLength={80} placeholder="My application" /></Field><Field label="Environment"><select name="environment"><option value="test">Test — simulated delivery</option><option value="production" disabled={!productionEnabled}>Production — {productionEnabled ? 'real email' : 'verified domain required'}</option></select></Field></div><Field label="Expires after"><select name="expiry"><option value="90">90 days</option><option value="30">30 days</option><option value="365">365 days</option><option value="0">No expiry</option></select></Field><fieldset className="live-checkboxes"><legend>Permissions</legend>{scopes.map(scope => <label key={scope}><input type="checkbox" name="scopes" value={scope} defaultChecked={['emails:send', 'emails:read'].includes(scope)} />{scope}</label>)}</fieldset><p className="muted">The environment isolates sending and email reads. Management scopes control shared workspace resources.</p><ErrorNotice error={action.error} /><Submit busy={action.busy}>Create API key</Submit></form></Panel>
    <Panel title="Active keys" action={<Refresh reload={list.reload} />}><ErrorNotice error={list.error} />{list.loading && <p>Loading keys…</p>}<div className="table-wrap"><table className="data-table"><thead><tr><th>Name</th><th>Prefix</th><th>Environment</th><th>Scopes</th><th>Actions</th></tr></thead><tbody>{list.result?.data.map(key => <tr key={key.id}><td>{key.name}</td><td><code>{key.prefix}…</code></td><td>{key.environment}</td><td>{key.scopes.join(', ')}</td><td className="live-actions"><button className="text-link" disabled={action.busy} onClick={() => { if (confirm(`Rotate ${key.name}? The old key stops working immediately.`)) action.run(async () => { const value = await api.post<Envelope<{ secret: string }>>(`/v1/api-keys/${key.id}/rotate`, {}); setSecret(value.data.secret); list.reload() }) }}>Rotate</button><button className="text-link" disabled={action.busy} onClick={() => { if (confirm(`Revoke ${key.name}?`)) action.run(async () => { await api.delete(`/v1/api-keys/${key.id}`); list.reload() }) }}>Revoke</button></td></tr>)}</tbody></table></div>{!list.loading && !list.result?.data.length && <p>No active keys.</p>}</Panel>{secret && <Secret value={secret} close={() => setSecret('')} />}</>
}
const events = ['email.delivery', 'email.bounce', 'email.complaint', 'email.reject', 'email.rendering_failure', 'email.open', 'email.click']
export function Webhooks() {
  const list = useResource<Endpoint[]>('/v1/webhooks'), action = useAction(), [secret, setSecret] = useState(''), [selected, setSelected] = useState<string | null>(null), [attemptId, setAttemptId] = useState<string | null>(null)
  const deliveries = useResource<Delivery[]>(selected ? `/v1/webhooks/${selected}/deliveries` : null, !!selected)
  const attempts = useResource<unknown[]>(selected && attemptId ? `/v1/webhooks/${selected}/deliveries/${attemptId}/attempts` : null)
  return <><Panel title="Add a webhook"><form className="form-stack" onSubmit={e => { e.preventDefault(); const form = e.currentTarget, data = new FormData(form); action.run(async () => { const value = await api.post<Envelope<{ secret: string }>>('/v1/webhooks', { url: data.get('url'), environment: data.get('environment'), subscriptions: data.getAll('events') }); setSecret(value.data.secret); form.reset(); list.reload() }) }}><div className="form-two"><Field label="HTTPS endpoint"><input name="url" type="url" placeholder="https://hooks.example.com/mailer" required /></Field><Field label="Environment"><select name="environment"><option value="test">Test</option><option value="production">Production</option></select></Field></div><fieldset className="live-checkboxes"><legend>Events</legend>{events.map(event => <label key={event}><input name="events" type="checkbox" value={event} defaultChecked={['email.delivery', 'email.bounce', 'email.complaint'].includes(event)} />{event}</label>)}</fieldset><p>Use a public DNS hostname and a trusted TLS certificate. IP addresses and private networks are blocked.</p><ErrorNotice error={action.error} /><Submit busy={action.busy}>Create endpoint</Submit></form></Panel>
    <Panel title="Webhook endpoints" action={<Refresh reload={list.reload} />}><ErrorNotice error={list.error} />{list.loading && <p>Loading endpoints…</p>}{list.result?.data.map(endpoint => <article className="live-record" key={endpoint.id}><strong>{endpoint.url}</strong><p>{endpoint.environment} · {endpoint.enabled ? 'Enabled' : 'Disabled'}</p><p className="muted">{endpoint.subscriptions.join(', ')}</p><div className="live-actions"><button className="text-link" onClick={() => { setSelected(endpoint.id); setAttemptId(null) }}>Delivery attempts</button><button className="text-link" disabled={action.busy} onClick={() => action.run(async () => { await api.patch(`/v1/webhooks/${endpoint.id}`, { enabled: !endpoint.enabled }); list.reload() })}>{endpoint.enabled ? 'Disable' : 'Enable'}</button><button className="text-link" disabled={action.busy} onClick={() => { if (confirm('Rotate the signing secret? Update your receiver immediately.')) action.run(async () => { const value = await api.post<Envelope<{ secret: string }>>(`/v1/webhooks/${endpoint.id}/rotate-secret`, {}); setSecret(value.data.secret) }) }}>Rotate secret</button><button className="text-link" disabled={action.busy} onClick={() => { if (confirm('Delete this endpoint and its delivery history?')) action.run(async () => { await api.delete(`/v1/webhooks/${endpoint.id}`); list.reload(); setSelected(null) }) }}>Delete</button></div></article>)}{!list.loading && !list.result?.data.length && <p>No webhook endpoints.</p>}</Panel>
    {selected && <Panel title="Latest 100 webhook deliveries" action={<Refresh reload={deliveries.reload} />}><ErrorNotice error={deliveries.error} />{deliveries.result?.data.map(delivery => <article key={delivery.id} className="live-record"><strong>{delivery.eventType}</strong> <Badge value={delivery.status} /><p>{date(delivery.createdAt)} · {delivery.attempts} attempts</p><ErrorNotice error={delivery.lastError} /><div className="live-actions"><button className="text-link" onClick={() => setAttemptId(delivery.id)}>Inspect attempts</button>{delivery.status === 'failed' && <button className="text-link" disabled={action.busy} onClick={() => action.run(async () => { await api.post(`/v1/webhooks/${selected}/deliveries/${delivery.id}/retry`, {}); deliveries.reload() })}>Retry delivery</button>}</div></article>)}{!deliveries.loading && !deliveries.result?.data.length && <p>No deliveries yet. Send a test email with a test endpoint subscribed to email.delivery.</p>}{attemptId && <><ErrorNotice error={attempts.error} /><pre>{JSON.stringify(attempts.result?.data, null, 2)}</pre></>}</Panel>}{secret && <Secret value={secret} close={() => setSecret('')} />}</>
}
export function Suppressions() {
  const [offset, setOffset] = useState(0), list = useResource<Suppression[]>(`/v1/suppressions?limit=50&offset=${offset}`), action = useAction()
  return <Panel title="Recipient suppressions" action={<Refresh reload={list.reload} />}><p>Suppressions block sending across this workspace. Remove only after resolving the cause and confirming consent.</p><form className="live-inline-form" onSubmit={e => { e.preventDefault(); const form = e.currentTarget, address = new FormData(form).get('address'); action.run(async () => { await api.post('/v1/suppressions', { address }); form.reset(); list.reload() }) }}><Field label="Email address"><input type="email" name="address" required /></Field><Submit busy={action.busy}>Suppress recipient</Submit></form><ErrorNotice error={action.error || list.error} />{list.loading && <p>Loading…</p>}<div className="table-wrap"><table className="data-table"><thead><tr><th>Address</th><th>Reason</th><th>Added</th><th /></tr></thead><tbody>{list.result?.data.map(item => <tr key={item.id}><td>{item.address}</td><td>{item.reason}</td><td>{date(item.createdAt)}</td><td><button className="text-link" disabled={action.busy} onClick={() => { if (confirm(`Allow sending to ${item.address} again? Confirm validity and consent.`)) action.run(async () => { await api.delete(`/v1/suppressions/${item.id}`); list.reload() }) }}>Remove</button></td></tr>)}</tbody></table></div>{!list.loading && !list.result?.data.length && <p>No suppressions.</p>}<div className="live-actions"><button className="button button--secondary" disabled={!offset} onClick={() => setOffset(Math.max(0, offset - 50))}>Previous</button><button className="button button--secondary" disabled={!list.result?.hasMore} onClick={() => setOffset(offset + 50)}>Next</button></div></Panel>
}
