import { useState } from 'react'
import { ArrowUpRight, Check, CheckCircle2, Clock3, CreditCard, KeyRound, Moon, Plus, Save, ScrollText, ShieldCheck, SlidersHorizontal, Sun, UserPlus, Users, X } from 'lucide-react'

type Section = 'general' | 'team' | 'security' | 'audit'
type Member = { id: string; initials: string; name: string; email: string; role: string; activity: string; tone?: string }
const initialMembers: Member[] = [{ id: 'alex', initials: 'AM', name: 'Alex Morgan', email: 'alex@acme.dev', role: 'Owner', activity: 'Active now' }, { id: 'priya', initials: 'PS', name: 'Priya Shah', email: 'priya@acme.dev', role: 'Developer', activity: 'Active 2h ago', tone: 'green' }, { id: 'marcus', initials: 'ML', name: 'Marcus Lee', email: 'marcus@acme.dev', role: 'Analyst', activity: 'Active yesterday', tone: 'amber' }]

export function SettingsPage() { const [section, setSection] = useState<Section>('general'); const [members, setMembers] = useState(initialMembers); const [inviteOpen, setInviteOpen] = useState(false); const [saved, setSaved] = useState(false); const nav: { id: Section; label: string; icon: typeof SlidersHorizontal }[] = [{ id: 'general', label: 'General', icon: SlidersHorizontal }, { id: 'team', label: 'Team and roles', icon: Users }, { id: 'security', label: 'Security', icon: ShieldCheck }, { id: 'audit', label: 'Audit log', icon: ScrollText }]; return <div className="settings-layout"><nav className="settings-nav" aria-label="Settings sections">{nav.map(item => <button className={`settings-nav__item ${section === item.id ? 'settings-nav__item--active' : ''}`} key={item.id} onClick={() => setSection(item.id)}><item.icon size={15} />{item.label}</button>)}</nav><div className="settings-content">{section === 'general' && <General onSave={() => setSaved(true)} saved={saved} />}{section === 'team' && <Team members={members} onInvite={() => setInviteOpen(true)} />}{section === 'security' && <Security />}{section === 'audit' && <Audit />}</div>{inviteOpen && <InviteMember onClose={() => setInviteOpen(false)} onInvite={member => { setMembers(current => [...current, member]); setInviteOpen(false) }} />}</div> }

function General({ onSave, saved }: { onSave: () => void; saved: boolean }) { const [name, setName] = useState('Acme Cloud'); const [slug, setSlug] = useState('acme-cloud'); const [theme, setTheme] = useState<'light' | 'dark'>('light'); return <section className="settings-section"><div className="settings-section__heading"><div><h2>General</h2><p>Workspace identity and interface preferences.</p></div><button className="button button--primary" onClick={onSave}><Save size={14} />{saved ? 'Saved' : 'Save changes'}</button></div><article className="panel settings-card"><div className="settings-field"><div><strong>Workspace name</strong><span>Shown to your team in the workspace switcher.</span></div><input value={name} onChange={event => setName(event.target.value)} /></div><div className="settings-field"><div><strong>Workspace slug</strong><span>Used in internal links and API metadata.</span></div><div className="settings-input-prefix"><span>signalmail.dev/</span><input value={slug} onChange={event => setSlug(event.target.value)} /></div></div><div className="settings-field"><div><strong>Interface theme</strong><span>Choose the appearance for this console.</span></div><div className="theme-toggle"><button className={`theme-choice ${theme === 'light' ? 'theme-choice--active' : ''}`} onClick={() => setTheme('light')}><Sun size={13} />Light</button><button className={`theme-choice ${theme === 'dark' ? 'theme-choice--active' : ''}`} onClick={() => setTheme('dark')}><Moon size={13} />Dark</button></div></div></article></section> }

function Team({ members, onInvite }: { members: Member[]; onInvite: () => void }) { const [roles, setRoles] = useState<Record<string, string>>({}); return <section className="settings-section"><div className="settings-section__heading"><div><h2>Team and roles</h2><p>Invite collaborators and control workspace access.</p></div><button className="button button--secondary" onClick={onInvite}><UserPlus size={14} />Invite member</button></div><article className="panel team-card">{members.map(member => <div className="team-row" key={member.id}><span className={`team-avatar ${member.tone ? `team-avatar--${member.tone}` : ''}`}>{member.initials}</span><span className="team-person"><strong>{member.name}</strong><small>{member.email}</small></span><select className="role-badge" value={roles[member.id] ?? member.role} disabled={member.role === 'Owner'} onChange={event => setRoles(current => ({ ...current, [member.id]: event.target.value }))}><option>Owner</option><option>Developer</option><option>Analyst</option></select><span className="team-last">{member.activity}</span><button className="icon-button icon-button--small" aria-label={`Manage ${member.name}`}><MoreDots /></button></div>)}</article></section> }

function MoreDots() { return <span aria-hidden="true" style={{ letterSpacing: 2 }}>...</span> }
function Security() { const [mfa, setMfa] = useState(true); const [duration, setDuration] = useState('30 days'); return <section className="settings-section"><div className="settings-section__heading"><div><h2>Security</h2><p>Protect your workspace and account.</p></div></div><article className="panel security-card"><div className="security-row"><span className="security-row__icon security-row__icon--green"><KeyRound size={14} /></span><span><strong>Two-factor authentication</strong><small>Required for owners and admins.</small></span><span className={`status status--${mfa ? 'delivered' : 'pending'}`}><i>{mfa ? <Check size={12} /> : <Clock3 size={12} />}</i>{mfa ? 'Enabled' : 'Optional'}</span><button className="button button--secondary" onClick={() => setMfa(value => !value)}>{mfa ? 'Disable' : 'Enable'}</button></div><div className="security-row"><span className="security-row__icon"><Clock3 size={14} /></span><span><strong>Session duration</strong><small>Sessions expire after inactivity.</small></span><select className="security-value" value={duration} onChange={event => setDuration(event.target.value)}><option>7 days</option><option>30 days</option><option>90 days</option></select></div><div className="security-row"><span className="security-row__icon"><KeyRound size={14} /></span><span><strong>API key rotation</strong><small>Last workspace rotation was 12 days ago.</small></span><strong className="security-value">Healthy</strong><button className="button button--secondary">Review</button></div></article></section> }
function Audit() { const entries = [['Created a new API key', 'Production API', '2 min ago'], ['Verified domain', 'notify.acme.dev', 'Yesterday'], ['Invited a team member', 'marcus@acme.dev', 'Aug 12, 2026']]; const [query, setQuery] = useState(''); return <section className="settings-section"><div className="settings-section__heading"><div><h2>Audit log</h2><p>Recent changes made in this workspace.</p></div><div className="search-field search-field--compact"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Filter activity" /></div></div><article className="panel audit-card">{entries.filter(entry => entry.join(' ').toLowerCase().includes(query.toLowerCase())).map(([title, detail, time]) => <div className="audit-row" key={title}><span className="audit-icon"><CheckCircle2 size={14} /></span><span><strong>{title}</strong><small>{detail}</small></span><time>{time}</time></div>)}</article></section> }

function InviteMember({ onClose, onInvite }: { onClose: () => void; onInvite: (member: Member) => void }) { const [email, setEmail] = useState(''); const [role, setRole] = useState('Developer'); return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="invite-title"><div className="modal__header"><div><p className="eyebrow">Workspace access</p><h2 id="invite-title">Invite a team member</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={16} /></button></div><form className="form-stack" onSubmit={event => { event.preventDefault(); const name = email.split('@')[0]; onInvite({ id: `member_${Date.now()}`, initials: name.slice(0, 2).toUpperCase(), name, email, role, activity: 'Invitation pending' }) }}><label className="field"><span>Email address</span><input type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="teammate@acme.dev" required /></label><label className="field"><span>Role</span><select value={role} onChange={event => setRole(event.target.value)}><option>Developer</option><option>Analyst</option></select></label><div className="modal__footer"><button className="button button--secondary" type="button" onClick={onClose}>Cancel</button><button className="button button--primary" type="submit"><UserPlus size={14} />Send invitation</button></div></form></section></div> }

