[package]
name = "cs-mail-auth"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
argon2.workspace = true
base64.workspace = true
hmac.workspace = true
rand.workspace = true
sha2.workspace = true
uuid.workspace = true
url.workspace = true
