import { useMemo, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import {
  Activity, AlertCircle, ArrowUpRight, Bell, Check, CheckCheck, ChevronDown, ChevronRight,
  ChevronsUpDown, CircleHelp, Clock3, Download, FileCode2, Globe2, KeyRound, LayoutDashboard,
  LogOut, Mail, Menu, Plus, Search, Send, Settings2, ShieldBan, Timer, TrendingDown, TrendingUp,
  X
} from 'lucide-react'
import { navGroups, routeFromPath, routeTitles, routes, type AppRoute as Route } from './app/routes'
import { emailFixtures as emails } from './features/emails/fixtures'
import { EmailsPage } from './features/emails/EmailsPage'
import { DomainsPage } from './features/domains/DomainsPage'
import { ApiKeysPage } from './features/api-keys/ApiKeysPage'
import { WebhooksPage } from './features/webhooks/WebhooksPage'
import { TemplatesPage } from './features/templates/TemplatesPage'
import { SuppressionsPage } from './features/suppressions/SuppressionsPage'
import { SettingsPage } from './features/settings/SettingsPage'
import { BillingPage } from './features/billing/BillingPage'
import { AuthPage, OnboardingPage, authModeFromPath } from './features/auth/AuthPage'

type Icon = typeof Activity
function useRoute(): [Route, (route: Route) => void] {
  const location = useLocation()
  const routerNavigate = useNavigate()
  return [routeFromPath(location.pathname), (route) => routerNavigate(routes[route])]
}

function Status({ value }: { value: string }) {
  const kind = value === 'Delivered' ? 'delivered' : value === 'Bounced' ? 'bounced' : 'pending'
  return <span className={`status status--${kind}`}><i>{kind === 'delivered' ? <Check size={12} /> : kind === 'bounced' ? <X size={12} /> : <Clock3 size={12} />}</i>{value}</span>
}

function Sidebar({ route, navigate, mobileOpen, onClose }: { route: Route; navigate: (route: Route) => void; mobileOpen: boolean; onClose: () => void }) {
  const [open, setOpen] = useState(false)
  const go = (next: Route) => { navigate(next); onClose() }
  return <aside className={`sidebar ${mobileOpen ? 'is-open' : ''}`} id="sidebar">
    <div className="sidebar__top"><a className="brand" href="#overview"><span className="brand__mark">S</span><span className="brand__name">signal<span>mail</span></span></a><button className="icon-button sidebar__close" onClick={onClose} aria-label="Close navigation"><X size={16} /></button></div>
    <div className="workspace-switcher"><div className="workspace-switcher__avatar">AC</div><div className="workspace-switcher__copy"><span className="eyebrow">Workspace</span><strong>Acme Cloud</strong></div><ChevronsUpDown size={15} /></div>
    <nav className="nav" aria-label="Primary navigation">{navGroups.map(group => <div key={group.label}><span className="nav__label">{group.label}</span>{group.items.map(item => <button key={item.route} className={`nav__item ${route === item.route ? 'nav__item--active' : ''}`} onClick={() => go(item.route)}><item.icon size={15} /><span>{item.label}</span>{item.count && <span className="nav__count">{item.count}</span>}</button>)}</div>)}</nav>
    <div className="sidebar__bottom"><div className="usage-card"><div className="usage-card__heading"><span>Monthly usage</span><Activity size={14} /></div><strong>184,290 <span>/ 250k</span></strong><div className="progress"><span style={{ width: '73.7%' }} /></div><div className="usage-card__footer"><span>73.7% used</span><button onClick={() => navigate('billing')}>Manage plan</button></div></div>
      {open && <div className="profile-popover" role="menu"><button onClick={() => go('settings')}><Settings2 size={14} />Settings</button><button onClick={() => go('billing')}><Activity size={14} />Billing</button><button onClick={() => setOpen(false)}><LogOut size={14} />Sign out</button></div>}
      <button className="profile-link" aria-expanded={open} onClick={() => setOpen(v => !v)}><span className="profile-link__avatar">AM</span><span className="profile-link__copy"><strong>Alex Morgan</strong><small>Owner</small></span><ChevronDown className={open ? 'is-rotated' : ''} size={16} /></button>
    </div>
  </aside>
}

function Topbar({ route, setOpen }: { route: Route; setOpen: () => void }) {
  const title = routeTitles[route]
  return <header className="topbar"><button className="icon-button menu-trigger" onClick={setOpen} aria-label="Open navigation"><Menu size={17} /></button><div className="breadcrumb"><span>Workspace</span><ChevronRight size={13} /><strong>{title}</strong></div><div className="topbar__actions"><button className="icon-button" aria-label="Search"><Search size={16} /></button><button className="icon-button has-indicator" aria-label="Notifications"><Bell size={16} /><span /></button><div className="topbar__divider" /><button className="avatar-button">AM</button></div></header>
}

function PageHeader({ route, onSend }: { route: Route; onSend: () => void }) {
  const copy: Record<Route, [string, string, string]> = {
    overview: ['Tuesday, August 18, 2026', 'Good morning, Alex', 'Here is what is happening across your sending infrastructure.'], emails: ['Message activity', 'Emails', 'Inspect every message and delivery event in your workspace.'], domains: ['Sending infrastructure', 'Domains', 'Verify and monitor the domains you send from.'], templates: ['Reusable content', 'Templates', 'Build consistent, versioned email content for your product.'], webhooks: ['Event delivery', 'Webhooks', 'Connect delivery events to the systems your team owns.'], 'api-keys': ['Developer access', 'API keys', 'Create scoped credentials for your sending integrations.'], suppressions: ['Reputation controls', 'Suppressions', 'Keep bounced and opted-out recipients out of your sends.'], settings: ['Workspace configuration', 'Settings', 'Manage members, security, and workspace activity.'], billing: ['Plan and usage', 'Billing', 'Manage your plan, payment method, and invoices.']
  }
  const [eyebrow, title, sub] = copy[route]
  return <section className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="page-heading__sub">{sub}</p></div><div className="page-heading__actions">{route === 'overview' && <button className="button button--secondary"><Download size={15} />Export</button>}{['overview', 'emails'].includes(route) && <button className="button button--primary" onClick={onSend}><Plus size={15} />Send email</button>}{!['overview', 'emails'].includes(route) && <button className="button button--primary"><Plus size={15} />Create new</button>}</div></section>
}

function Overview({ navigate }: { navigate: (route: Route) => void }) {
  const metrics: { label: string; value: string; trend: string; icon: Icon; color: string }[] = [
    { label: 'Emails sent', value: '184,290', trend: '12.8%', icon: TrendingUp, color: 'blue' }, { label: 'Delivery rate', value: '99.42%', trend: '0.18%', icon: TrendingUp, color: 'green' },
    { label: 'Bounce rate', value: '0.31%', trend: '0.07%', icon: TrendingDown, color: 'amber' }, { label: 'Avg. delivery time', value: '1.8s', trend: '0.4s', icon: TrendingDown, color: 'violet' }
  ]
  return <><section className="metric-grid" aria-label="Email performance">{metrics.map(({ label, value, trend, icon: Trend, color }) => <article className="metric-card" key={label}><div className="metric-card__top"><span className="metric-card__label">{label}</span><span className={`metric-icon metric-icon--${color}`}><Activity size={15} /></span></div><strong className="metric-card__value">{value}</strong><div className="metric-card__trend metric-card__trend--up"><Trend size={13} /> {trend} <span>vs. last month</span></div></article>)}</section>
    <section className="content-grid content-grid--primary"><article className="panel chart-panel"><div className="panel__header"><div><h2>Sending activity</h2><p>Volume and delivery performance over the last 30 days</p></div><button className="select-button">Last 30 days <ChevronDown size={14} /></button></div><div className="chart-legend"><span><i className="legend-dot legend-dot--blue" />Sent</span><span><i className="legend-dot legend-dot--green" />Delivered</span></div><div className="chart" role="img" aria-label="Sending activity chart"><div className="chart__y-axis"><span>15k</span><span>10k</span><span>5k</span><span>0</span></div><div className="chart__plot"><div className="chart__gridline" style={{ top: 0 }} /><div className="chart__gridline" style={{ top: '33.33%' }} /><div className="chart__gridline" style={{ top: '66.66%' }} /><div className="chart__gridline" style={{ top: '100%' }} /><svg className="chart__svg" viewBox="0 0 720 220" preserveAspectRatio="none"><path className="chart__area" d="M0 179 C27 166 39 174 61 158 S96 155 121 143 S153 157 180 130 S220 134 240 119 S276 121 300 109 S336 118 361 95 S394 101 420 87 S458 93 480 73 S513 81 540 65 S575 74 600 50 S639 58 660 39 S697 41 720 22 L720 220 L0 220Z" /><path className="chart__line chart__line--blue" d="M0 179 C27 166 39 174 61 158 S96 155 121 143 S153 157 180 130 S220 134 240 119 S276 121 300 109 S336 118 361 95 S394 101 420 87 S458 93 480 73 S513 81 540 65 S575 74 600 50 S639 58 660 39 S697 41 720 22" /></svg><div className="chart__x-axis"><span>Jul 20</span><span>Jul 25</span><span>Jul 30</span><span>Aug 04</span><span>Aug 09</span><span>Aug 14</span><span>Aug 18</span></div></div></div></article><article className="panel health-panel"><div className="panel__header"><div><h2>Sending health</h2><p>Current status across your domains</p></div><button className="text-link" onClick={() => navigate('domains')}>View domains <ArrowUpRight size={14} /></button></div><div className="health-score"><div className="health-score__ring"><span>98</span><small>/100</small></div><div><strong>Excellent</strong><p>Your sending reputation is healthy.</p></div></div><div className="health-list">{[['SPF records', '3 / 3', 'green'], ['DKIM signatures', '3 / 3', 'green'], ['DMARC policy', '2 / 3', 'amber'], ['Suppression rate', '0.08%', 'green']].map(([label, val, c]) => <div className="health-row" key={label}><span><i className={`status-dot status-dot--${c}`} />{label}</span><strong>{val}</strong></div>)}</div></article></section>
    <section className="panel activity-panel"><div className="panel__header"><div><h2>Recent activity</h2><p>The latest messages moving through your account</p></div><button className="text-link" onClick={() => navigate('emails')}>View all emails <ArrowUpRight size={14} /></button></div><EmailTable compact /></section></>
}

function EmailTable({ compact = false }: { compact?: boolean }) { return <div className="table-wrap"><table className="data-table"><thead><tr><th>Message</th><th>Recipient</th><th>Domain</th><th>Status</th><th>Sent</th><th /></tr></thead><tbody>{emails.slice(0, compact ? 5 : emails.length).map(({ subject, recipient, domain, status, sentAt, id }) => <tr key={subject}><td><div className="message-cell"><span className="message-cell__icon"><Mail size={14} /></span><span><strong>{subject}</strong><code>{id}</code></span></div></td><td>{recipient}</td><td><code>{domain}</code></td><td><Status value={status} /></td><td className="muted">{sentAt}</td><td><button className="icon-button icon-button--small" aria-label="Open message"><ArrowUpRight size={14} /></button></td></tr>)}</tbody></table></div> }

function GenericPage({ route }: { route: Route }) { const [query, setQuery] = useState(''); const items = route === 'domains' ? [['mail.acme.dev', 'Verified', '184,290 sent'], ['notify.acme.dev', 'Verified', '23,104 sent'], ['updates.acme.dev', 'Action required', '0 sent']] : route === 'api-keys' ? [['Production key', 'Active', 'Created Aug 12, 2026'], ['Local development', 'Active', 'Created Jul 28, 2026']] : route === 'webhooks' ? [['Delivery events', 'Healthy', 'Last delivery 2 min ago'], ['Bounce alerts', 'Healthy', 'Last delivery 14 min ago']] : [['Noah Williams', 'Owner', 'noah@acme.dev'], ['Maya Chen', 'Developer', 'maya@acme.dev']]; const filtered = items.filter(item => item.join(' ').toLowerCase().includes(query.toLowerCase())); return <section className="panel route-placeholder"><div className="panel__header"><div><h2>{route === 'domains' ? 'Your domains' : route === 'api-keys' ? 'Credentials' : route === 'webhooks' ? 'Endpoints' : route === 'templates' ? 'Saved templates' : route === 'suppressions' ? 'Suppressed recipients' : 'Workspace members'}</h2><p>Manage this part of your developer mail workspace.</p></div><div className="table-actions"><div className="search-field"><Search size={14} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search" /></div></div></div>{route === 'templates' ? <div className="empty-state"><span className="empty-state__icon"><FileCode2 size={17} /></span><h2>No templates yet</h2><p>Create your first reusable email template to keep product messages consistent.</p><button className="button button--primary"><Plus size={14} />Create template</button></div> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Name</th><th>Status</th><th>Details</th><th /></tr></thead><tbody>{filtered.map(([name, status, detail]) => <tr key={name}><td><strong>{name}</strong></td><td><Status value={status === 'Verified' || status === 'Active' || status === 'Healthy' ? 'Delivered' : 'Processing'} /></td><td className="muted">{detail}</td><td><button className="icon-button icon-button--small" aria-label="Open"><ArrowUpRight size={14} /></button></td></tr>)}</tbody></table></div>}</section> }

export default function App() {
  const location = useLocation(); const authMode = authModeFromPath(location.pathname); const [route, navigate] = useRoute(); const [sidebarOpen, setSidebarOpen] = useState(false); const [sendOpen, setSendOpen] = useState(false)
  const page = useMemo(() => route === 'overview' ? <Overview navigate={navigate} /> : route === 'emails' ? <EmailsPage /> : route === 'domains' ? <DomainsPage /> : route === 'api-keys' ? <ApiKeysPage /> : route === 'webhooks' ? <WebhooksPage /> : route === 'templates' ? <TemplatesPage /> : route === 'suppressions' ? <SuppressionsPage /> : route === 'settings' ? <SettingsPage /> : route === 'billing' ? <BillingPage /> : <GenericPage route={route} />, [route])
  if (authMode) return <AuthPage mode={authMode} />
  if (location.pathname === '/onboarding') return <OnboardingPage />
  return <div className="app-shell"><Sidebar route={route} navigate={navigate} mobileOpen={sidebarOpen} onClose={() => setSidebarOpen(false)} /><main className="main-content"><Topbar route={route} setOpen={() => setSidebarOpen(true)} /><div className="page-wrap react-page"><PageHeader route={route} onSend={() => setSendOpen(true)} />{page}<footer className="page-footer"><span>Signal Mail <span className="footer-dot">.</span> All systems operational</span><span>Last updated just now</span></footer></div></main>{sidebarOpen && <button className="mobile-sidebar-backdrop" onClick={() => setSidebarOpen(false)} aria-label="Close navigation" />}{sendOpen && <SendDialog close={() => setSendOpen(false)} />}</div>
}

function SendDialog({ close }: { close: () => void }) { const [sent, setSent] = useState(false); return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="send-title"><div className="modal__header"><div><p className="eyebrow">Quick action</p><h2 id="send-title">Send a test email</h2></div><button className="icon-button" onClick={close} aria-label="Close"><X size={16} /></button></div>{sent ? <div className="success-state"><span className="success-state__icon"><CheckCheck size={17} /></span><div><h2>Email queued</h2><p>Your test message is now processing.</p><button className="button button--primary" onClick={close}>Done</button></div></div> : <form className="form-stack" onSubmit={e => { e.preventDefault(); setSent(true) }}><label className="field"><span>From</span><select><option>Acme Cloud &lt;hello@mail.acme.dev&gt;</option></select></label><label className="field"><span>To</span><input type="email" placeholder="you@example.com" required /></label><label className="field"><span>Subject</span><input defaultValue="A test email from Signal Mail" required /></label><label className="field"><span>Message</span><textarea rows={4} defaultValue="This is a test message sent from your Signal Mail workspace." /></label><div className="modal__footer"><button className="button button--secondary" type="button" onClick={close}>Cancel</button><button className="button button--primary" type="submit"><Send size={14} />Send test</button></div></form>}</section></div> }
