import { useState } from 'react'
import { ArrowUpRight, Check, Copy, KeyRound, LockKeyhole, MoreHorizontal, Pause, Plus, RotateCcw, Server, Terminal, X } from 'lucide-react'
import { apiKeyFixtures, type ApiKeySummary } from './fixtures'

function KeyStatus({ value }: { value: ApiKeySummary['status'] }) { return <span className={`status status--${value === 'Active' ? 'delivered' : 'pending'}`}><i>{value === 'Active' ? <Check size={12} /> : <Pause size={12} />}</i>{value}</span> }

export function ApiKeysPage() {
  const [keys, setKeys] = useState(apiKeyFixtures)
  const [createOpen, setCreateOpen] = useState(false)
  const [newSecret, setNewSecret] = useState<string | null>(null)
  const [revokeId, setRevokeId] = useState<string | null>(null)
  const revoke = () => { if (revokeId) { setKeys(current => current.filter(key => key.id !== revokeId)); setRevokeId(null) } }
  return <><section className="security-banner"><div className="security-banner__icon"><LockKeyhole size={16} /></div><div><strong>Keep your secret keys private</strong><p>Keys grant access to your workspace. Store them in environment variables and rotate them regularly.</p></div><button className="text-link">Read the docs <ArrowUpRight size={14} /></button></section><section className="panel keys-panel"><div className="panel__header"><div><h2>Workspace keys</h2><p>Only the key prefix is visible after creation.</p></div><button className="button button--primary" onClick={() => setCreateOpen(true)}><Plus size={14} />Create API key</button></div><div className="table-wrap"><table className="data-table keys-table"><thead><tr><th>Name</th><th>Key</th><th>Permissions</th><th>Created by</th><th>Last used</th><th>Status</th><th /></tr></thead><tbody>{keys.map(key => <tr key={key.id}><td><div className="key-name"><span className={`key-name__icon ${key.environment === 'Test' ? 'key-name__icon--muted' : ''}`}>{key.environment === 'Test' ? <Terminal size={14} /> : <Server size={14} />}</span><span><strong>{key.name}</strong><small>{key.description}</small></span></div></td><td><code>{key.prefix}</code></td><td><span className="permission-tag">{key.permission}</span></td><td>{key.createdBy}</td><td className="muted">{key.lastUsed}</td><td><KeyStatus value={key.status} /></td><td><button className="icon-button icon-button--small" onClick={() => setRevokeId(key.id)} aria-label={`Manage ${key.name}`}><MoreHorizontal size={14} /></button></td></tr>)}</tbody></table></div><div className="keys-footer"><span>{keys.length} keys in this workspace</span><button className="text-link">View key audit log <ArrowUpRight size={14} /></button></div></section><section className="panel key-guidance"><Guidance number="1" title="Use separate keys per environment" copy="Keep production, staging, and local development access isolated." /><Guidance number="2" title="Grant the minimum permissions" copy="Send-only keys are safer for most application integrations." /><Guidance number="3" title="Rotate when systems change" copy="Revoke unused keys immediately and issue a replacement." /></section>{createOpen && <CreateKeyDialog onClose={() => setCreateOpen(false)} onCreated={(secret, key) => { setKeys(current => [key, ...current]); setCreateOpen(false); setNewSecret(secret) }} />}{newSecret && <SecretDialog secret={newSecret} onClose={() => setNewSecret(null)} />}{revokeId && <ConfirmRevoke name={keys.find(key => key.id === revokeId)?.name ?? 'this key'} onCancel={() => setRevokeId(null)} onConfirm={revoke} />}</>
}

function Guidance({ number, title, copy }: { number: string; title: string; copy: string }) { return <div className="key-guidance__item"><span className="key-guidance__number">{number}</span><div><strong>{title}</strong><p>{copy}</p></div></div> }

function CreateKeyDialog({ onClose, onCreated }: { onClose: () => void; onCreated: (secret: string, key: ApiKeySummary) => void }) {
  const [name, setName] = useState('')
  const [environment, setEnvironment] = useState<ApiKeySummary['environment']>('Production')
  const [permission, setPermission] = useState('Send only')
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="key-title"><div className="modal__header"><div><p className="eyebrow">Developer access</p><h2 id="key-title">Create an API key</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={16} /></button></div><form className="form-stack" onSubmit={event => { event.preventDefault(); const suffix = Math.random().toString(36).slice(2, 6); onCreated(`sk_${environment === 'Production' ? 'live' : 'test'}_${Math.random().toString(36).slice(2, 18)}${suffix}`, { id: `key_${Date.now()}`, name: name.trim() || 'Untitled key', description: `${environment} integration`, prefix: `sk_${environment === 'Production' ? 'live' : 'test'}_........${suffix}`, permission, environment, createdBy: 'Alex Morgan', lastUsed: 'Never', status: 'Active' }) }}><label className="field"><span>Key name</span><input value={name} onChange={event => setName(event.target.value)} placeholder="Production API" required /></label><label className="field"><span>Environment</span><select value={environment} onChange={event => setEnvironment(event.target.value as ApiKeySummary['environment'])}><option>Production</option><option>Test</option></select></label><label className="field"><span>Permissions</span><select value={permission} onChange={event => setPermission(event.target.value)}><option>Send only</option><option>Read only</option><option>Full access</option></select></label><p className="form-hint"><KeyRound size={14} />The complete secret is shown once. It cannot be recovered later.</p><div className="modal__footer"><button className="button button--secondary" type="button" onClick={onClose}>Cancel</button><button className="button button--primary" type="submit"><KeyRound size={14} />Create key</button></div></form></section></div>
}

function SecretDialog({ secret, onClose }: { secret: string; onClose: () => void }) { const [copied, setCopied] = useState(false); const copy = async () => { await navigator.clipboard?.writeText(secret); setCopied(true) }; return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="secret-title"><div className="modal__header"><div><p className="eyebrow">One-time secret</p><h2 id="secret-title">Save your API key</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={16} /></button></div><div className="secret-field"><code>{secret}</code><button className="icon-button icon-button--small" onClick={copy} aria-label="Copy secret"><Copy size={14} /></button></div><p className="form-hint">{copied ? 'Copied to clipboard.' : 'Store this key in a secret manager. For security, it will not be shown again.'}</p><div className="modal__footer"><button className="button button--primary" onClick={onClose}>Done</button></div></section></div> }

function ConfirmRevoke({ name, onCancel, onConfirm }: { name: string; onCancel: () => void; onConfirm: () => void }) { return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="revoke-title"><div className="modal__header"><div><p className="eyebrow">Destructive action</p><h2 id="revoke-title">Revoke API key?</h2></div><button className="icon-button" onClick={onCancel} aria-label="Close"><X size={16} /></button></div><p className="modal-copy">Any service using <strong>{name}</strong> will stop authenticating immediately. This cannot be undone.</p><div className="modal__footer"><button className="button button--secondary" onClick={onCancel}>Cancel</button><button className="button button--danger" onClick={onConfirm}><RotateCcw size={14} />Revoke key</button></div></section></div> }

